version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: Asia/Tokyo
