version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  cooldown:
    default-days: 5
    include:
      - "*"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  groups:
    aws/aws-sdk-go-v2:
      patterns:
        - "github.com/aws/aws-sdk-go-v2"
        - "github.com/aws/aws-sdk-go-v2/*"
    mackerelio:
      patterns:
        - "github.com/mackerelio/*"
    k8s:
      patterns:
        - "k8s.io/*"
  cooldown:
    default-days: 5
    include:
      - "*"
    exclude:
      - "github.com/mackerelio/*"
      - "github.com/aws/aws-sdk-go-v2"
      - "github.com/aws/aws-sdk-go-v2/*"
      - "k8s.io/*"
- package-ecosystem: gomod
  directory: "/plugins"
  schedule:
    interval: daily
    time: "17:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  groups:
    mackerelio:
      patterns:
        - "github.com/mackerelio/*"
  cooldown:
    default-days: 5
    include:
      - "*"
    exclude:
      - "github.com/mackerelio/*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Asia/Tokyo
  cooldown:
    default-days: 5
    include:
      - "*"
