FROM golang:1.17-stretch

WORKDIR /go/src/app

COPY go.sum go.mod ./
RUN go mod download

COPY . .
RUN make build

FROM debian:stretch-slim AS container-agent

ENV DEBIAN_FRONTEND noninteractive
ENV GODEBUG http2client=0

RUN apt-get update -yq && \
    apt-get install -yq --no-install-recommends ca-certificates sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists

COPY --from=0 /go/src/app/build/mackerel-container-agent /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/mackerel-container-agent"]

