ARG REPOSITORY
ARG TAG

FROM $REPOSITORY:$TAG

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -yq && \
    apt-get install -yq --no-install-recommends curl gnupg2
RUN echo "deb [arch=amd64] http://apt.mackerel.io/v2/ mackerel contrib" > /etc/apt/sources.list.d/mackerel.list
RUN curl -LfsS https://mackerel.io/file/cert/GPG-KEY-mackerel-v2 | apt-key add -

RUN apt-get update -yq && \
    apt-get install -yq --no-install-recommends mackerel-agent-plugins mackerel-check-plugins && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists
