---
name: ci/cd

permissions:
  contents: read
  id-token: write
  packages: write

on:
  pull_request: {}
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-
      - run: make test

  build-and-push-alpha:
    if: startsWith(github.head_ref, 'bump-version-')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to Docker Hub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: "mackerel-container-agent-${{ github.run_id }}-${{ github.run_number }}"
          aws-region: ap-northeast-1
      - name: Login to Public ECR
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: public.ecr.aws
        env:
          AWS_REGION: us-east-1

      - name: Login to GHCR
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get alpha version from branch name
        id: get_alpha_version
        run: echo "VERSION=${GITHUB_HEAD_REF/bump-version-/v}" >> "$GITHUB_OUTPUT"

      - name: Build and push alpha image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: Dockerfile
          target: container-agent
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            mackerel/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-alpha
            public.ecr.aws/mackerel/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-alpha
            ghcr.io/${{ github.repository_owner }}/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-alpha

      - name: Build and push alpha image with plugins
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: Dockerfile
          target: container-agent-with-plugins
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            mackerel/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-plugins-alpha
            public.ecr.aws/mackerel/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-plugins-alpha
            ghcr.io/${{ github.repository_owner }}/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-plugins-alpha

  build-and-push-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to Docker Hub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: "mackerel-container-agent-${{ github.run_id }}-${{ github.run_number }}"
          aws-region: ap-northeast-1
      - name: Login to Public ECR
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: public.ecr.aws
        env:
          AWS_REGION: us-east-1

      - name: Login to GHCR
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"

      - name: Build and push release image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: Dockerfile
          target: container-agent
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            mackerel/mackerel-container-agent:latest
            mackerel/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}
            public.ecr.aws/mackerel/mackerel-container-agent:latest
            public.ecr.aws/mackerel/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/mackerel-container-agent:latest
            ghcr.io/${{ github.repository_owner }}/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}

      - name: Build and push release image with plugins
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: Dockerfile
          target: container-agent-with-plugins
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            mackerel/mackerel-container-agent:plugins
            mackerel/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}-plugins
            public.ecr.aws/mackerel/mackerel-container-agent:plugins
            public.ecr.aws/mackerel/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}-plugins
            ghcr.io/${{ github.repository_owner }}/mackerel-container-agent:plugins
            ghcr.io/${{ github.repository_owner }}/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}-plugins
