name: "Create Release PR"
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "next release version"
        required: true
env:
  GIT_AUTHOR_NAME: mackerelbot
  GIT_AUTHOR_EMAIL: mackerelbot@users.noreply.github.com
  GIT_COMMITTER_NAME: mackerelbot
  GIT_COMMITTER_EMAIL: mackerelbot@users.noreply.github.com

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: mackerelio/mackerel-create-release-pull-request-action@main
        id: start
        with:
          github_token: ${{ secrets.MACKERELBOT_GITHUB_TOKEN }}
          next_version: ${{ github.event.inputs.release_version }}
          package_name: mackerel-container-agent
          ignore_update_program_files: "true"

      - uses: mackerelio/mackerel-create-release-pull-request-action@main
        with:
          github_token: ${{ secrets.MACKERELBOT_GITHUB_TOKEN }}
          finished: "true"
          package_name: mackerel-container-agent
          next_version: ${{ steps.start.outputs.nextVersion }}
          branch_name: ${{ steps.start.outputs.branchName }}
          pull_request_infos: ${{ steps.start.outputs.pullRequestInfos }}
